# Generated by Django 4.2.17 on 2025-01-28 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngridientModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit', models.TextField(choices=[('граммы', 'граммы'), ('килограммы', 'килограммы'), ('миллилитры', 'миллилитры'), ('литры', 'литры'), ('штуки', 'штуки')])),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipe.recipemodel')),
            ],
        ),
    ]
